### PR TITLE
Initial app/server setup

### PR DESCRIPTION
**Pull request by kguinto**
Initialized Express server to build and serve a basic React app with Webpack & Babel

### CODE REVIEW

**Comment by kguinto** [comment]
@zinoki @Kyle-Chambers @emsando @bdduong 
Any comments on this setup? OK to merge?

**Comment by emsando** [comment]
Is there a way to have github give notifications (inside github) whenever anyone makes a pull request inside the "organization"? That way we know when things are ready for review?

**Comment by kguinto** [comment]
Maybe in [here](https://github.com/settings/notifications)? Taking that as an OK lol

**Comment by zinoki** [comment]
@kguinto I approve this merge

**Comment by kguinto** [comment]
🙏 🙏 🙏

**Pull request merged**
